<a href="https://colab.research.google.com/github/TAM-DS/TAM-DS/blob/main/ann_for_combinedcyclepowerplant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Overview:  

Implemented a Artifical Neural Network in Python (Regression) model to predict the electrical energy output of the Combined Cycle Power Plant.

A combined-cycle power plant is an electrical power plant in which a Gas Turbine (GT) and a Steam Turbine (ST) are used in combination to produce more electrical energy from the same fuel than that would be possible from a single cycle power plant.

The gas turbine compresses air and mixes it with a fuel heated to a very high temperature. The hot air-fuel mixture moves through the blades, making them spin. The fast-spinning gas turbine drives a generator to generate electricity. The exhaust (waste) heat escaped through the exhaust stack of the gas turbine is utilized by a Heat Recovery Steam Generator (HSRG) system to produce steam that spins a steam turbine. This steam turbine drives a generator to produce additional electricity. CCCP is assumed to produce 50% more energy than a single power plant.

Inputs were Temp, Pressure, Humidity & Vacuum

Included 2 layers of 6 Units (input, hidden)

Outerlayer is 1 unit.

Results were that the Predicted Results we incredibly close to the Test results.



# Artificial Neural Network

### Importing the libraries

## Part 1 - Data Preprocessing

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

### Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,  :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 0)

## Part 2 - Building the ANN

## Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

#Part 3 Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam' , loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 21481.5234
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 389.0297
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 366.0210
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 338.1915
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 307.5694
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 276.0315
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 243.6661
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 211.6770
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 181.5466
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 153.8855
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 129.0954
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

60/60 [==============================] - 0s 1ms/step
[[433.16 431.23]
 [462.23 460.01]
 [467.09 461.14]
 ...
 [474.14 473.26]
 [438.98 438.  ]
 [459.38 463.28]]
